### ISSUE TITLE
Sequence server takes exceedingly long time to echo ready in docker-compose environment

### ISSUE THREAD

**Issue by mjy** [wurmlab/sequenceserver#509]
When I configure SS in a docker-compose.yml, then when I do `docker-compose up`, it takes an exceedingly long time to prepare (> 10 minutes).  Having a hard time debugging this, so thought I'd at least mention it here.

The same configuration (I *think*, `sequenceserver -b /usr/local/ncbi/blast/bin/ -d data`), running natively, is "instantaneously" ready. 

My conf:

```
---
:num_threads: 4
:frame_options: sameorigin
:host: 0.0.0.0
:port: 4567
:bin: "/blast/bin"
:database_dir: "/db"
```

My docker-compose.yml:

```
version: "3"
services:
  web:
    image: nginx:latest
    container_name: nginx_web
    build:
      context: .
      dockerfile: Dockerfile.development
    ports:
      - 80:80 # local:docker
    volumes: # mount root directory from this machine to the container itself (live development, e.g. Rails sees changes to files without rebuilding container0
      - ./site:/site
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
    stdin_open: true
    tty: true
    restart: unless-stopped
    depends_on:
      - sequenceserver
      - jbrowse
  sequenceserver:
    build:
      context: .
      dockerfile: Dockerfile.sequenceserver
    tty: true # added 2021
    stdin_open: true # added 2021
    volumes:
      - ./data:/db
      - ./config/sequenceserver/sequenceserver.conf:/root/.sequenceserver.conf
      - ./config/sequenceserver/links.rb:/links.rb
  jbrowse:
    build:
      context: .
      dockerfile: Dockerfile.jbrowse
    ports:
      - "8081:80"
    env_file:
      - ./config/jbrowse/env.conf
    volumes:
      - ./config/jbrowse/jbrowse.conf:/conda/opt/jbrowse/jbrowse.conf # root/.sequenceserver.conf
      - ./data:/conda/opt/jbrowse/data
```

My Dockerfile.sequenceserver:

```
FROM wurmlab/sequenceserver:2.0.0.rc8
```
