### ISSUE TITLE
Migrate testing from Travis to Github Actions

### ISSUE THREAD

**Issue by yannickwurm** [wurmlab/sequenceserver#653]
This is because Travis is unreliable/unstable and delayed/badly integrated. 

Going forwards, we only need ruby 3 / 3.2 to work. (2.x is deprecated). 

The following ruby.yml GitHub action (from a different repo) may help. 

```
name: Ruby & Rspec

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['2.6', '3.2']

    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - name: Run rubocop
        run: bundle exec rubocop
      - name: Run tests
        env:
          STRIPE_API_KEY: ${{ secrets.STRIPE_API_KEY }}
        run: bundle exec rspec spec

      - name: Artifacts
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: build-artifacts
          path: |
            coverage/
          if-no-files-found: error
```
